DROP TABLE IF EXISTS documents;
CREATE TABLE documents (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  body TEXT NOT NULL,
  mtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  active INTEGER NOT NULL
);

DROP TABLE IF EXISTS metadata;
CREATE TABLE metadata (
  document_name TEXT NOT NULL,
  key TEXT NOT NULL,
  value TEXT NOT NULL
);
